### ISSUE TITLE
Må kunne sende inn inaktive typer

### ISSUE THREAD

**Issue by jorgkv** [NVE/regobslib#2]
Vi må kunne sende inn inaktive typer.

Et eksempel er `AvalancheObs.Type` der man må kunne sende inn TID 20 som er *Slab avalanche*.

Jeg er litt usikker på om vi skal legge til dette i Enumene, eller bare "gjøre det mulig" å sende inn heltall ved å angi feks

```python
class DangerSign(Observation):

    def __init__(self,
                 sign: Optional[Union[DangerSign.Sign, int]] = None,
                 comment: Optional[str] = None):
        ...
```

Evt bare angi `int`, men da får man ikke hjelp av type hints.

**Comment by widforss** [comment]
Men begge de to løsningene vil ødelegge avhengig kode når man pensjonerer et skjema. Det eneste som ikke gjør det er å ha alle variantene i f.eks. AvalancheObs.Type. Men da vil vi ikke kunne signalere via typsystemet at man bruker gamle skjeman. Men man kan jo lage en guard i f.eks. konstruktorn til AvalancheObs som printer ut noe til stderr.

**Comment by jorgkv** [comment]
Jeg tror vi kan bare legge til de som jeg vet blir brukt i AvalancheObs.Type. Mulig det bare er to stk det er snakk om. Jeg kan lage en pr på det.
