### ISSUE TITLE
Possibility to set ObserverGroupID and ObserverGroupName

### ISSUE THREAD

**Issue by develmusa** [NVE/regobslib#25]
The possibility to set ObserverGroupID and ObserverGroupName when registering an observation is missing in `regobslib`.

In the code I see that the observer has a variable `competence`. However, it does not appear in the Swagger documentation example: https://test-api.regobs.no/v5/swagger/ui/index#/Registration/Registration_Insert

Is there a full documentation with description of the key that the API supports?

**Comment by danielgratzl** [comment]
Any chance this PR will be merged eventually?
